import { Brain } from "lucide-react";
import { cn } from "@/lib/utils";
import type { CollaborationMessage } from "@/types/collaboration";
import { ProtocolSnippetCard } from "@/components/collaboration/shared/ProtocolSnippetCard";
import { TaskCard } from "@/components/collaboration/shared/TaskCard";
import { ViewSourcesPanel } from "@/components/collaboration/shared/ViewSourcesPanel";

interface AIMessageBubbleProps {
  message: CollaborationMessage;
  mode?: "messages" | "threads";
}

export function AIMessageBubble({ message, mode = "threads" }: AIMessageBubbleProps) {
  const embedded = (message.embeddedContent || {}) as Record<string, any>;
  const isMessageMode = mode === "messages";

  return (
    <div className={cn("space-y-2", isMessageMode ? "max-w-[860px]" : "max-w-[80%]")}>
      {!isMessageMode ? (
        <div className="flex items-center gap-2 pl-0.5 text-sm">
          <span className="inline-flex h-8 w-8 items-center justify-center rounded-full border border-neutral-300 bg-white text-neutral-700">
            <Brain className="h-4 w-4" />
          </span>
          <span className="font-semibold text-neutral-900">Themison AI</span>
          <span className="rounded-lg bg-neutral-200 px-2 py-1 text-xs text-neutral-600">Generated by Themison AI</span>
        </div>
      ) : (
        <div className="inline-flex items-center gap-1.5 rounded-full border border-gray-300 bg-white px-2.5 py-1 text-[11px] font-semibold text-gray-700 shadow-sm">
          <Brain className="h-3.5 w-3.5" />
          Themison AI
        </div>
      )}

      <div
        className={cn(
          "rounded-3xl border border-neutral-300 bg-white px-4 py-3 shadow-sm",
          isMessageMode ? "border-gray-300 bg-[#f9f9fa]" : "bg-white"
        )}
      >
        <p className={cn("whitespace-pre-wrap text-sm text-neutral-800", isMessageMode && "text-[13px] leading-[1.5] text-gray-800")}>
          {message.content}
        </p>

        {message.contentType === "protocol_snippet" && embedded.document_name ? (
          <div className="mt-2">
            <ProtocolSnippetCard
              documentName={String(embedded.document_name)}
              sectionRef={String(embedded.section_ref || "Section")}
              quotedText={String(embedded.quoted_text || "")}
              documentLink={embedded.document_link ? String(embedded.document_link) : undefined}
              aiGenerated
              variant={isMessageMode ? "messages" : "default"}
            />
          </div>
        ) : null}

        {message.contentType === "task_card" && embedded.title ? (
          <div className="mt-2">
            <TaskCard
              title={String(embedded.title)}
              assigneeName={embedded.assignee_name ? String(embedded.assignee_name) : undefined}
              dueDate={embedded.due_date ? String(embedded.due_date) : undefined}
              status={embedded.status ? String(embedded.status) : undefined}
              headline={isMessageMode ? "Task Created" : "Action suggestion"}
              requiresConfirmation
              variant={isMessageMode ? "messages" : "default"}
            />
          </div>
        ) : null}

        <ViewSourcesPanel sources={embedded.sources || []} />

        {isMessageMode ? (
          <div className="mt-2 text-[10px] font-semibold uppercase tracking-wide text-gray-500">
            Generated by Themison AI
          </div>
        ) : null}
      </div>
    </div>
  );
}
